# File: /dotfiles/shell/bashrc

# Bash configuration file

# Set up environment variables
# export EDITOR=nano
# export VISUAL=nano

# # Aliases
# alias ll='ls -la'
# alias gs='git status'
# alias gp='git pull'
# alias gc='git commit'

# # Functions
# mkcd() {
#     mkdir -p "$1" && cd "$1"
# }

# # Prompt customization
# PS1='[\u@\h \W]\$ ' 

# # Load additional scripts if they exist
# if [ -f ~/.bash_aliases ]; then
#     . ~/.bash_aliases
# fi

# if [ -f ~/.bash_functions ]; then
#     . ~/.bash_functions
# fi

# export SHELL=/bin/zsh
# exec zsh